excluded:
  - "**/*/Generated/*"
  - "Sources/Preview Content/*"

included:
  - Sources
  - Tests
  - UITests

analyzer_rules:
  - unused_import

disabled_rules:
  # - line_length
  - trailing_whitespace
  - todo

opt_in_rules:
  - attributes
  - closure_body_length
  # - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_object_literal
  - discouraged_optional_boolean
  - duplicate_imports
  - empty_count
  - empty_string
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - for_where
  - force_unwrapping
  - function_parameter_count
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - modifier_order
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unused_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces

# Rule configurations

closure_body_length:
  warning: 50
  error: 80

cyclomatic_complexity:
  ignores_case_statements: true

empty_count:
  only_after_dot: true

force_cast: error

force_try: error

file_length:
  warning: 300
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 120

function_parameter_count:
  warning: 8
  error: 15
  ignores_default_parameters: true

identifier_name:
  excluded:
    - i
    - id
    - at
    - up
    - vc
    - to
    - x
    - y
  
large_tuple:
  warning: 3
  error: 8

line_length:
  warning: 200
  error: 300
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 4
    error: 6

type_body_length:
  warning: 300
  error: 500

type_name:
  excluded:
    - T
